-- Geração de Modelo físico
-- Sql ANSI 2003 - brModelo.



CREATE TABLE Matricula (
RA INTEGER,
RC INTEGER,
Data DATE,
Status TINYINT,
PRIMARY KEY(RA,RC)
)

CREATE TABLE Curso (
RC INTEGER PRIMARY KEY,
Status TINYINT,
titulo VARCHAR(50),
Descricao VARCHAR(150)
)

CREATE TABLE Telefone (
CPF BIGINT(),
Telefone BIGINT(14),
PRIMARY KEY(CPF,Telefone)
)

CREATE TABLE Pessoa (
CPF BIGINT(14) PRIMARY KEY,
RG VARCHAR(20),
Bairro VARCHAR(50),
Cidade VARCHAR(60),
Estado CHAR(2),
Rua VARCHAR(200),
CEP CHAR(9),
Primeiro Nome VARCHAR(255),
Data de Nascimento DATE,
Sobrenome VARCHAR(255),
Senha VARCHAR(20)
)

CREATE TABLE Professor (
RP INTEGER PRIMARY KEY,
CPF BIGINT(),
Status TINYINT,
FOREIGN KEY(CPF) REFERENCES Pessoa (CPF)
)

CREATE TABLE Administrador (
RAD INTEGER PRIMARY KEY,
CPF BIGINT(),
status TINYINT,
FOREIGN KEY(CPF) REFERENCES Pessoa (CPF)
)

CREATE TABLE Email (
CPF BIGINT(),
Email VARCHAR(100),
PRIMARY KEY(CPF,Email),
FOREIGN KEY(CPF) REFERENCES Pessoa (CPF)
)

CREATE TABLE Aviso (
RA INTEGER,
RAD INTEGER,
aviso_text VARCHAR(250),
Data DATE,
PRIMARY KEY(RA,RAD),
FOREIGN KEY(RAD) REFERENCES Administrador (RAD)
)

CREATE TABLE Aluno (
RA INTEGER PRIMARY KEY,
CPF BIGINT(),
status TINYINT,
Qualificacoes VARCHAR(250),
FOREIGN KEY(CPF) REFERENCES Pessoa (CPF)
)

CREATE TABLE Materia (
RM INTEGER PRIMARY KEY,
RC INTEGER,
RP INTEGER,
Avaliacoes VARCHAR(250),
ExtraClasse VARCHAR(250),
Material VARCHAR(250),
Bibliografia VARCHAR(250),
Titulo VARCHAR(50),
Apresentacao VARCHAR(250),
Objetivo VARCHAR(255),
Ementa TEXT,
Status TINYINT,
Data_inicio DATE,
Data_Final DATE,
FOREIGN KEY(RC) REFERENCES Curso (RC),
FOREIGN KEY(RP) REFERENCES Professor (RP)
)

CREATE TABLE Avaliado (
RA INTEGER,
RM INTEGER,
Data DATE,
Nota DECIMAL(2,2 ),
Tipo VARCHAR(30),
PRIMARY KEY(RA,RM),
FOREIGN KEY(RA) REFERENCES Aluno (RA),
FOREIGN KEY(RM) REFERENCES Materia (RM)
)

CREATE TABLE Frequenta (
RA INTEGER,
RM INTEGER,
Data DATE,
Presenca TINYINT,
PRIMARY KEY(RA,RM),
FOREIGN KEY(RA) REFERENCES Aluno (RA),
FOREIGN KEY(RM) REFERENCES Materia (RM)
)

CREATE TABLE Aula (
RM INTEGER PRIMARY KEY,
horario_final TIME,
horario_inicio TIME,
Nome_Turma VARCHAR(30),
Turno VARCHAR(30),
FOREIGN KEY(RM) REFERENCES Materia (RM)
)

CREATE TABLE Diasemana (
RM INTEGER PRIMARY KEY,
Domingo VARCHAR(),
Segunda VARCHAR(),
Terca VARCHAR(),
Quarta VARCHAR(),
Quinta VARCHAR(),
Sexta VARCHAR(),
Sabado VARCHAR(),
FOREIGN KEY(RM) REFERENCES Aula (RM)
)

ALTER TABLE Matricula ADD FOREIGN KEY(RA) REFERENCES Aluno (RA)
ALTER TABLE Matricula ADD FOREIGN KEY(RC) REFERENCES Curso (RC)
ALTER TABLE Telefone ADD FOREIGN KEY(CPF) REFERENCES Pessoa (CPF)
ALTER TABLE Aviso ADD FOREIGN KEY(RA) REFERENCES Aluno (RA)
